// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.penho.java.rool;

import com.penho.java.rool.SysRoleDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SysRoleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SysRoleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SysRoleIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: SysRoleIntegrationTest: @Transactional;
    
    @Autowired
    private SysRoleDataOnDemand SysRoleIntegrationTest.dod;
    
    @Test
    public void SysRoleIntegrationTest.testCountSysRoles() {
        org.junit.Assert.assertNotNull("Data on demand for 'SysRole' failed to initialize correctly", dod.getRandomSysRole());
        long count = com.penho.java.rool.SysRole.countSysRoles();
        org.junit.Assert.assertTrue("Counter for 'SysRole' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SysRoleIntegrationTest.testFindSysRole() {
        com.penho.java.rool.SysRole obj = dod.getRandomSysRole();
        org.junit.Assert.assertNotNull("Data on demand for 'SysRole' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'SysRole' failed to provide an identifier", id);
        obj = com.penho.java.rool.SysRole.findSysRole(id);
        org.junit.Assert.assertNotNull("Find method for 'SysRole' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'SysRole' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SysRoleIntegrationTest.testFindAllSysRoles() {
        org.junit.Assert.assertNotNull("Data on demand for 'SysRole' failed to initialize correctly", dod.getRandomSysRole());
        long count = com.penho.java.rool.SysRole.countSysRoles();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'SysRole', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.penho.java.rool.SysRole> result = com.penho.java.rool.SysRole.findAllSysRoles();
        org.junit.Assert.assertNotNull("Find all method for 'SysRole' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'SysRole' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SysRoleIntegrationTest.testFindSysRoleEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'SysRole' failed to initialize correctly", dod.getRandomSysRole());
        long count = com.penho.java.rool.SysRole.countSysRoles();
        if (count > 20) count = 20;
        java.util.List<com.penho.java.rool.SysRole> result = com.penho.java.rool.SysRole.findSysRoleEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'SysRole' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'SysRole' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SysRoleIntegrationTest.testFlush() {
        com.penho.java.rool.SysRole obj = dod.getRandomSysRole();
        org.junit.Assert.assertNotNull("Data on demand for 'SysRole' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'SysRole' failed to provide an identifier", id);
        obj = com.penho.java.rool.SysRole.findSysRole(id);
        org.junit.Assert.assertNotNull("Find method for 'SysRole' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySysRole(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'SysRole' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SysRoleIntegrationTest.testMerge() {
        com.penho.java.rool.SysRole obj = dod.getRandomSysRole();
        org.junit.Assert.assertNotNull("Data on demand for 'SysRole' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'SysRole' failed to provide an identifier", id);
        obj = com.penho.java.rool.SysRole.findSysRole(id);
        boolean modified =  dod.modifySysRole(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.penho.java.rool.SysRole merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'SysRole' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SysRoleIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'SysRole' failed to initialize correctly", dod.getRandomSysRole());
        com.penho.java.rool.SysRole obj = dod.getNewTransientSysRole(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'SysRole' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'SysRole' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'SysRole' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SysRoleIntegrationTest.testRemove() {
        com.penho.java.rool.SysRole obj = dod.getRandomSysRole();
        org.junit.Assert.assertNotNull("Data on demand for 'SysRole' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'SysRole' failed to provide an identifier", id);
        obj = com.penho.java.rool.SysRole.findSysRole(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'SysRole' with identifier '" + id + "'", com.penho.java.rool.SysRole.findSysRole(id));
    }
    
}
