// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.penho.java.rool;

import java.lang.String;

privileged aspect SysRole_Roo_JavaBean {
    
    public String SysRole.getRoleName() {
        return this.roleName;
    }
    
    public void SysRole.setRoleName(String roleName) {
        this.roleName = roleName;
    }
    
}
